### ISSUE TITLE
plugin crashing on Linux

### ISSUE THREAD

**Issue by pawlowska** [pierre-weiss/VSNR_2D-3D_GPU#4]
I compiled the VSNR plugin under Linux. Both 2D and 3D versions start, allow me to select the Parametrization and number of Iterations, and then the entire Fiji crashes. There is no error message, but a hs_err_pidXXX.log gets created in the Fiji directory. What can be hapenning?

The error log starts with:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdb102e604e, pid=14325, tid=0x00007fdbbc8b9700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.172-b11 mixed mode linux-amd64 )
# Problematic frame:
# C  [libcublas.so.9.1+0x7e04e]
```

**Comment by pierre-weiss** [comment]
Dear Monika,

nice to hear that you managed to compile the codes. I haven't touched this
code for a long time now.

From the error message you sent though (libcublas.so.9.1+0x7e04e), I
suspect that your CUDA library might not be installed properly. From what I
remember, you should have CUBLAS and CUFFT properly installed
https://developer.nvidia.com/gpu-accelerated-libraries

I am currently working under Ubuntu 20.04 and it seems you can install
these packages directly from synaptic or apt. I don't know for the prior
versions. In any cases, you should be able to find the run files on the
NVIDIA website.

I hope this helps!
Best,
Pierre

**Comment by pawlowska** [comment]
I'm indeed not very familiar with CUDA libraries. I installed nvcc via apt-get. What else do I need and how to check if it's installed?

In general, for CUDA beginners like me it would be very helpful to write explicitely what libraries are required and which version. Before trying Linux, I installed the plugin on another machine, with Windows, and there I had this issue:
https://github.com/pierre-weiss/VSNR_2D-3D_GPU/issues/1
I have CUDA toolkit installed on that other machine and I was able to run some other code (in Python, using cupy). So this is all a bit confusing to me.

**Comment by pawlowska** [comment]
(update: on Windows, I had CUDA v10. Installing v8 helped. So stating which version is required and/or allowing newer versions would be veeery helpful)

**Comment by pierre-weiss** [comment]
Dear Monika,

I just tried to make a complete installation on a brand new system with Ubuntu 20.04 and an RTX 8000. What I did was: 
- Select latest proprietary drivers for the NVIDIA card.
- sudo apt update
- sudo apt install nvidia-cuda-toolkit

Then I followed the steps in the README.txt to compile the code in 2D and 3D. Everything seems to have worked nicely both in 2D and 3D. 

The precompiled libraries that we provided a few years ago (probably with old CUDA architectures) will most likely not work with a recent system. But I faced no trouble reinstalling the plugin, which was a relief. 

It was a real struggle installing nvidia drivers and toolkit a few years ago, but with the new 20.04 release, it just became super simple. In case you still face issues, a possibility would be to upgrade your Linux version. 
Best,
Pierre

**Comment by pawlowska** [comment]
Okay. I'm using Ubuntu 18.04, so not that old. nvidia-cuda-toolkit was already installed - I have version 9.1.85-3ubuntu1. I didn't have the proprietary driver, but on open source one, so I installed the proprietary. However, I'm getting the same error. Do I need to compile the library again?

**Comment by pawlowska** [comment]
Update: the plugin indeed works better after updateing to Ubuntu 20.04 and updating nvidia, so I'm closing this issue

**Comment by pierre-weiss** [comment]
Oh yeah ! Thanks for the notice !
